# Generated by Django 4.2.16 on 2024-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('artist_description', models.TextField()),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
