# Generated by Django 4.2.16 on 2024-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_alter_video_artist_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(max_length=500),
        ),
    ]
